version: '3.9'

services:
  eureka-service:
    build:
      context: ./eureka-service
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - app-network

  api-gateway:    
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-service
      - auth-service
      - car-service
      - lease-rate-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka
    networks:
      - app-network

  auth-service:
    build:
      context: ./authservice
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    networks:
      - app-network

  car-service:
    build:
      context: ./car-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    networks:
      - app-network

  customer-service:
    build:
      context: ./customer-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    networks:
      - app-network

  lease-rate-service:
    build:
      context: ./lease-rate-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_SERVER_URL=http://eureka-service:8761/eureka
    depends_on:
      - eureka-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
