server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: car-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/cars/**
        - id: customer-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/customers/**
        - id: lease-rate-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/lease-rates/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    hostname: localhost

logging:
  level:
    org.springframework.cloud.gateway: DEBUG